version : '3'
services:
  router:
    environment:
    - 'PORT=80'
    - 'NAME=router'
    - 'API_KEY=API'
    image: router:micro-front
    depends_on:
      - mongo
    ports:
    - '8080:80'
  mongo:
    image: mongo
    restart: always
  header:
    environment:
    - 'PORT=80'
    - 'NAME=header'
    image: header:micro-front
  footer:
    environment:
    - 'PORT=80'
    - 'NAME=footer'
    image: footer:micro-front


